
package BAR;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 * @author Axel Yamir CT
 */
public class TIENDA_BAR extends javax.swing.JFrame {
  
    private String dato;
    
    public TIENDA_BAR() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        Image icono= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/coctel.png"));
        this.setIconImage(icono);
        
        Image fondo= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/fondobar.jpg"));
        jlbFondoTienda.setIcon(new ImageIcon(fondo.getScaledInstance(jlbFondoTienda.getWidth(), jlbFondoTienda.getHeight() , Image.SCALE_SMOOTH ) ));
        Image logo= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/carnaval.png"));
        lblLogo.setIcon(new ImageIcon(logo.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight() , Image.SCALE_SMOOTH ) ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnVentas = new javax.swing.JButton();
        BtnVentas1 = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jlbFondoTienda = new javax.swing.JLabel();
        lblRecibeDni = new javax.swing.JLabel();
        lblRecibeApellido = new javax.swing.JLabel();
        lblRecibeNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVentas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        BtnVentas.setText("REALIZAR VENTA");
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 250, 70));

        BtnVentas1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BtnVentas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usua.png"))); // NOI18N
        BtnVentas1.setText("AÑADIR CLIENTE");
        BtnVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentas1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, 70));
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, 240));
        getContentPane().add(jlbFondoTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));

        lblRecibeDni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecibeDni.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblRecibeDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, 40));

        lblRecibeApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecibeApellido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblRecibeApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 40));

        lblRecibeNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecibeNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblRecibeNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
         VENTAS a=new VENTAS();
            a.setVisible(true);
            String info=lblRecibeNombre.getText();
        VENTAS.jtlblNombreC.setText(info);
        
            String info2=lblRecibeApellido.getText();
        VENTAS.jtlblApellidoC.setText(info2);
        
            String info3=lblRecibeDni.getText();
        VENTAS.jtlblDniC.setText(info3);
            this.dispose();
         
    }//GEN-LAST:event_BtnVentasActionPerformed

    private void BtnVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentas1ActionPerformed
        AñadirCliente añadir=new AñadirCliente();
            añadir.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BtnVentas1ActionPerformed

    /**
     * @param args the command line arguments
     */


    public void setDato(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVentas;
    private javax.swing.JButton BtnVentas1;
    private javax.swing.JLabel jlbFondoTienda;
    private javax.swing.JLabel lblLogo;
    public static javax.swing.JLabel lblRecibeApellido;
    public static javax.swing.JLabel lblRecibeDni;
    public static javax.swing.JLabel lblRecibeNombre;
    // End of variables declaration//GEN-END:variables
}
