
package LOGIN;

import BAR.TIENDA_BAR;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import BaseDatos.EntidadVendedor;
import BaseDatos.VendedorDAO;

/**
 * @author Axel Yamir CT
 */
public class Formulario_Login extends javax.swing.JFrame {
    
    VendedorDAO vdao=new VendedorDAO();
    EntidadVendedor ev=new EntidadVendedor();

    public Formulario_Login() {
        initComponents();
        
        txtUsuario.setText("emp01");
        pasContraseña.setText("12345678");
        this.setLocationRelativeTo(this);
        this.setTitle("INGRESO DE SESIÓN DE CARNAVAL");
        //SetImageLabel(gaga, "src/img/Logo.png");
        
        
        Image icono= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/coctel.png"));
        this.setIconImage(icono);

        Image fondo= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/fondobar2.jpg"));
        jblFondo.setIcon(new ImageIcon(fondo.getScaledInstance(jblFondo.getWidth(), jblFondo.getHeight() , Image.SCALE_SMOOTH ) ));
        Image logo= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/carnaval.png"));
        jblLogo.setIcon(new ImageIcon(logo.getScaledInstance(jblLogo.getWidth(), jblLogo.getHeight() , Image.SCALE_SMOOTH ) ));
        Image iconito= Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/coctel.png"));
        jblIconito.setIcon(new ImageIcon(iconito.getScaledInstance(jblIconito.getWidth(), jblIconito.getHeight() , Image.SCALE_SMOOTH ) ));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jblLogo = new javax.swing.JLabel();
        jblFondo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        pasContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        jblIconito = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(jblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 210, 240));
        Background.add(jblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 270, 430));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("USUARIO");
        Background.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContraseña.setText("CONTRASEÑA");
        Background.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        Background.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 310, -1));
        Background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, 20));

        pasContraseña.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        pasContraseña.setForeground(new java.awt.Color(204, 204, 204));
        pasContraseña.setText("**********");
        pasContraseña.setBorder(null);
        pasContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pasContraseñaMousePressed(evt);
            }
        });
        pasContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasContraseñaActionPerformed(evt);
            }
        });
        Background.add(pasContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, -1));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 20));

        jPanel1.setBackground(new java.awt.Color(151, 120, 93));

        lblInicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jblIconito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInicio)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblIconito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInicio))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 90));

        jButton1.setBackground(new java.awt.Color(138, 101, 82));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, 50));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 424));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if (txtUsuario.getText().equals("Ingrese su nombre de usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(pasContraseña.getPassword()).isEmpty()){
            pasContraseña.setText("**********");
            pasContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed

    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pasContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasContraseñaMousePressed
        if (String.valueOf(pasContraseña.getPassword()).equals("**********")) {
            pasContraseña.setText("");
            pasContraseña.setForeground(Color.black);
        }
        if (txtUsuario.getText().isEmpty()){
            txtUsuario.setText("Ingrese su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pasContraseñaMousePressed

    private void pasContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasContraseñaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        validar();
    }//GEN-LAST:event_jButton1ActionPerformed

        public void validar(){
        String dni=pasContraseña.getText();
        String user=txtUsuario.getText();
        if(txtUsuario.getText().equals("")||pasContraseña.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar datos en las cajas Texto");
            txtUsuario.requestFocus();
        }else{
            ev=vdao.ValidarVendedor(dni,user);
            if(ev.getUser() != null && ev.getDni() != null){
                TIENDA_BAR p= new TIENDA_BAR();
                p.setVisible(true);
                dispose();
            }else {
                JOptionPane.showMessageDialog(this, "Intente otra vez");
                txtUsuario.requestFocus();
            }   
        }     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblIconito;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pasContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
